### ISSUE TITLE
Parallelism - CircleCI

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#1294]
## Why?
Test commands cannot be configured to run on designated branches (e.g. `branch: /feature_.*/`) - all tests are run for all branches. If additional tests are added (e.g. wraith or future initiatives), eventually we'll want the parallelism feature as an available option to alleviate build times. 

## Issue
Currently, builds fail when parallelism is enabled because multidev deployments are configured as a project dependency. Dependency commands are executed simultaneously across all virtual machines for the build, causing conflicts with terminus and rsync commands which result in a failed build.

## Solution
Remove `deploy-multidev.sh` from dependencies and include within deployments of `circle.yml`:
```
deployment:
  production:
    branch: master
    commands:
      - bash scripts/deploy-live.sh
  multidev:
    branch: /^(?!.*master).*$/
    commands:
      - bash scripts/deploy-multidev.sh
```
### Caveat
Multidevs would only be created/deployed after passing tests. If a failure occurs, the deployment would not be triggered. 

@bmackinney thoughts?
