### ISSUE TITLE
Drupal 8 and Composer on Pantheon Without Continuous Integration Doc Update 

### ISSUE THREAD

**Issue by daggerhart** [pantheon-systems/documentation#4263]
Re: [Drupal 8 and Composer on Pantheon Without Continuous Integration](https://pantheon.io/docs/guides/drupal-8-composer-no-ci/)

Priority: Low

## Issue Description:

More of a question than a recommendation. But should readers also delete the "workflows:" section of `pantheon.yml`?

That section looks like this in the example repo:
```
workflows:
  deploy_product:
    after:
      -
        type: webphp
        description: 'Run composer prepare-for-pantheon'
        script: private/scripts/deploy_product/prepare-for-pantheon.php
      -
        type: webphp
        description: 'Run composer install & drupal-scaffold'
        script: private/scripts/deploy_product/composer-install.php
  sync_code:
    after:
      - type: webphp
        description: Push changes back to GitHub if needed
        script: private/scripts/quicksilver/quicksilver-pushback/push-back-to-github.php
```

Not sure if this stuff is related to the continuous integration flow or if this show remain for all sites.

## Suggested Resolution

Either close this issue because I'm wrong, or add a section to the tutorial that recommends removing this part of the `pantheon.yml` file.
