### ISSUE TITLE
Glyphicons not appearing

### ISSUE THREAD

**Issue by jms-pantheon** [pantheon-systems/documentation#8261]
Re: [Using Git with SFTP & WordPress](https://docs.pantheon.io/guides/wordpress-git/plugins/) 

Looks like some missing icons here

![image](https://user-images.githubusercontent.com/91161717/226980697-92a614e1-55f7-40a7-bbb4-37260a3e5dde.png)

**Comment by EdwardAngert** [comment]
this might be a combination of an issue with the [gatsby plugin](https://www.npmjs.com/package/glyphicons-halflings) and L2-L5 in https://github.com/pantheon-systems/documentation/blob/main/src/styles/custom-glyphicons.css#L2-L5

which could be changed to the fonts directory, but that's not where the `.eot` is:

```css
@font-face {
  font-family:'Glyphicons Regular';
  src:url("/source/docs/assets/fonts/glyphicons/glyphicons-regular-v192.svg");
  src:url("/source/docs/assets/fonts/glyphicons/glyphicons-regular-v192.svg?#iefix") format('embedded-opentype'), url("/source/docs/assets/fonts/glyphicons/glyphicons-regular-v192.woff2") format('woff2'), url("/source/docs/assets/fonts/glyphicons/glyphicons-regular-v192.woff") format('woff'), url("/source/docs/assets/fonts/glyphicons/glyphicons-regular-v192.ttf") format('truetype'), url("/source/docs/assets/fonts/glyphicons/glyphicons-regular-v192.svg#glyphiconsregular") format('svg')}
```

the `.eot` can be found in `node_modules/bootstrap/fonts/glyphicons-halflings-regular.eot`

it'd be great to have it working again, but it also might be worth waiting for the redesign in which hopefully the icons the docs site uses are matched up with the rest of the Pantheon experience.
